Configure the URL of the repository to use when resolving the GE and CCUD plugins
c00ler/gradle-plugin pull request #1
Opened 2022-09-05 10:09 UTC by c00ler

…variable

2022-09-06 13:33 UTC, guylabs requested changes

2022-09-06 13:33 UTC, guylabs commented on README.adoc
> +|JENKINSGRADLEPLUGIN_GRADLE_PLUGIN_REPOSITORY_URL|Gradle|The URL of the repository to use when resolving the GE and CCUD plugins. Required if Jenkins agents are not able to access the Gradle Plugin P
```suggestion
|JENKINSGRADLEPLUGIN_GRADLE_PLUGIN_REPOSITORY_URL|Gradle|The URL of the repository to use when resolving the Gradle Enterprise Gradle plugin and the Common Custom User Data Gradle plugin. Required if Jenkins agents are not able to access the Gradle Plugin Portal at https://plugins.gradle.org.
```

2022-09-06 14:03 UTC, c00ler commented on README.adoc
> +|JENKINSGRADLEPLUGIN_GRADLE_PLUGIN_REPOSITORY_URL|Gradle|The URL of the repository to use when resolving the GE and CCUD plugins. Required if Jenkins agents are not able to access the Gradle Plugin P
Applied.

2022-09-06 14:29 UTC, facewindu approved these changes

2022-09-07 05:10 UTC, guylabs approved these changes

2022-09-07 06:18 UTC, welandaz approved these changes

2022-09-07 16:15 UTC, sorin-florea approved these changes

2022-09-08 06:30 UTC, sorin-florea approved these changes

2022-09-08 09:06 UTC, merged